trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatforms: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  project: './ExpanseTracker.csproj'

steps:
- task: NuGetToolInstaller@1
  name: 'NugetToolInstaller'
  displayName: 'Nuget tool installer'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(project)'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'