trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatforms: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  project: '**/*.csproj'

steps:
- task: NuGetToolInstaller@1
  name: 'NugetToolInstaller'
  displayName: 'Nuget tool installer'

- task: DotNetCoreCLI@2
  displayName: 'Restore' 
  inputs:
    command: 'restore'
    projects: '$(project)'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'BuildArtifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DotNetCoreCLI@2
  displayName: New Manifest for tool
  inputs:
    command: custom
    custom: 'new '
    arguments: tool-manifest

- task: DotNetCoreCLI@2
  displayName: Install EF Tool
  inputs:
    command: custom
    custom: 'tool'
    arguments: 'install --global dotnet-ef --version 6.0.2'
# Create SQL Script
- task: DotNetCoreCLI@2
  displayName: Create SQL Scripts
  inputs:
    command: custom
    custom: 'ef '
    arguments: 'migrations script --output $(sqlFile) --idempotent --project $(Build.SourcesDirectory)/ExpanseTracker/ExpanseTracker.csproj --context ApplicationDbContext'
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    projects: $(BuildParameters.RestoreBuildProjects)
    arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: SQLScripts'
  inputs:
    PathtoPublish: $(sqlFile)
    ArtifactName: SQLScripts
- task: SqlAzureDacpacDeployment@1
  displayName: Run migration script
  inputs:
    azureSubscription: 'Azure for Students(1)(bf4ce3da-7ad6-448c-87c9-93da8db009f4)'
    AuthenticationType: 'server'
    ServerName: '$(SqlServer-Name)'
    DatabaseName: 'ExpanseTracker'
    SqlUsername: '$(SqlServer-Username)'
    SqlPassword: '$(SqlServer-Password)'
    deployType: 'SqlTask'
    SqlFile: '$(sqlFile)'
    IpDetectionMethod: 'AutoDetect'